### ISSUE TITLE
where is the documentation?

### ISSUE THREAD

**Issue by Zaelee** [NetherGamesMC/ProxyTransport#5]
when I click on the link no documentation is displayed

**Comment by larryTheCoder** [comment]
The documentation link was removed, sorry about that. The plugin that were used as a communication bridge for this plugin is [ProxyTransport-PM](https://github.com/NetherGamesMC/ProxyTransport-PM). You can use this plugin in the PocketMine-MP side to connect using this plugin's protocol.
