### ISSUE TITLE
Connection sometimes would fail because of "Address already in use"

### ISSUE THREAD

**Issue by larryTheCoder** [NetherGamesMC/ProxyTransport#6]
![image](https://github.com/NetherGamesMC/ProxyTransport/assets/15889642/27fb1e0b-deaf-4a7e-91e5-c48bee3267c1)

**Comment by dries-c** [comment]
Fixed by https://github.com/NetherGamesMC/ProxyTransport/commit/ff23efd3dfd7d874c68bf15c25764931b6c900cf
